<?php
namespace Home\Controller;

class StoreController extends IndexController{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $result = self::findStore($_SESSION['mer_user']);
        $industry = self::getIndustry($result["industry_id"]);
        $this->assign([
            'name' => $result["name"],
            'bus_number' => $result["business_number"],
            'industry' => $industry["name"],
            'entity' => $result['industry_entity'],
            'description' => $result["description"],
            "ke_tel" => $result["ke_tel"],
            "wechat" => $result["wechat"],
            "open_hour" => $result["opening_hours"],
            'services' => $result["services"],
        ]);
        return $industry;
    }

    public function index() {
        $this->init();

        $this->display('Index/store');
    }


    public function edit() {
        $this->init();

        $industry = self::getIndustrys();
        $this->assign([
            "industry" => $industry
        ]);

        $this->display('Index/store-edit');
    }

}