<?php
namespace Home\Controller;
use Think\Exception;

class StoreController extends IndexController{
    protected $storeID;
    protected $storeInfo;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        // 行业ID
        $result = self::findStore($_SESSION['mer_user']);
        try{
            $industry = self::getIndustry($result["industry_id"]);
        }catch (Exception $e) {
            $industry = '';
        }
        $this->storeID = $result['id'];
        $this->storeInfo = $result;
        $this->assign([
            'name' => $result["name"],
            'bus_number' => $result["business_number"],
            'industry' => $industry["name"],
            'entity' => $result['industry_entity'],
            'description' => $result["description"],
            "ke_tel" => $result["ke_tel"],
            "wechat" => $result["wechat"],
            "open_hour" => $result["opening_hours"],
            'services' => $result["services"],
        ]);
        return $industry;
    }

    public function index() {
        $this->init();

        $this->display('Index/store');
    }

    public function edit() {
        $this->init();

        $industry = self::getIndustrys();
        $this->assign([
            "industry" => $industry,
            "nav_storePic" => U("store/pic"),
            "saveUrl" => U("store/saveBash"),
            'industry_id' => $this->storeInfo['industry_id'],
        ]);

        $this->display('Index/store-edit');
    }

    public function pic() {
        $this->init();

        $pic = self::getStorePic([]);


        $this->assign([
            'uploadAction' => ADMIN_HOST.'user/upload',
            'id' => I('session.mer_user'),
            'class' => 'store',
            'pic' => $pic
        ]);
        $this->display("Index/store-pic");
    }

    public function saveBash() {
        $this->init();
        $data = $_POST['data'];
        try {
            $result = self::saveStoreBash($this->storeID, $data);
        }catch (Exception $e){
            $this->ajaxReturn([
                'state' => false,
                'msg'   => '系统错误，请稍后重试'
            ]);
        }
        if ($result) {
            $this->ajaxReturn([
                'state' => true,
                'msg'   => '修改成功'
            ]);
        }else{
            $this->ajaxReturn([
                'state' => false,
                'msg'   => '修改失败'
            ]);
        }
    }

}